### ISSUE TITLE
Process finished with exit code -1073741571 (0xC00000FD)

### ISSUE THREAD

**Issue by BoyInTheSun** [BoyInTheSun/reversible_watermarking_algorithm#1]
`Windows`上运行Broader_following时会报错`Process finished with exit code -1073741571 (0xC00000FD)`，猜测是递归次数过多，栈溢出导致，暂无解决方案。
其他平台如`macOS`，`Debian`，`centOS`无此报错

**Comment by BoyInTheSun** [comment]
Process finished with exit code 137 (interrupted by signal 9: SIGKILL)
在Ubuntu上也有报错，仅在图片较大时发生，猜测也和递归次数过多有关

**Comment by BoyInTheSun** [comment]
目前已经解决，重写了broader_following函数，将大量递归更改为循环（仍用到递归，但减少了多个数量级）。
[Commits#481a92b](https://github.com/BoyInTheSun/reversible_watermarking_algorithm/commit/481a92bacb2fc68ba8dd52baa7a7339a8b51085f)

**Comment by MsFGz** [comment]
您好，对于broader_following函数我有些问题想向您请教一下

**Comment by BoyInTheSun** [comment]
> 您好，对于broader_following函数我有些问题想向您请教一下，希望可以联系到您

该代码仓库已烂尾，如果对算法感兴趣可以阅读原论文，感谢关注。
联系qq 3527857306
